// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdsfyrlopysxbrddlift.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkc2Z5cmxvcHlzeGJyZGRsaWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTk2NjQsImV4cCI6MjA4NTYzNTY2NH0.HRng5K6oF6f0cCYAq5qcXrow1zg0FM-s4ipdpzcWYrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});