// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgwanyretbrxwtwduljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnd2FueXJldGJyeHd0d2R1bGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODkwNDQsImV4cCI6MjA3MTM2NTA0NH0.1epHsTsOfI74BcSVn-RL8H9ZmpJQoyg75HlCZozG53Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});